import { Role, RoleKind, Capability, Scope } from '@/lib/types/domain';

// Institution Pack Roles (from §3.2)
export const INSTITUTION_ROLES: Omit<Role, 'id' | 'tenantId'>[] = [
  {
    key: 'PLATFORM_OPERATOR',
    title: 'Platform Operator',
    pack: 'INSTITUTION',
    rank: 0,
    kind: 'LINE',
    system: true,
    mayHoldReports: false,
    maxDelegableRank: 9,
    powerPresetId: 'preset-platform-operator',
    color: '#000000',
    icon: 'shield',
    sortOrder: 0,
  },
  {
    key: 'INSTITUTION_HEAD',
    title: 'Principal / Director',
    pack: 'INSTITUTION',
    rank: 1,
    kind: 'LINE',
    system: true,
    mayHoldReports: true,
    maxDelegableRank: 9,
    powerPresetId: 'preset-institution-head',
    color: '#366092',
    icon: 'crown',
    sortOrder: 1,
  },
  {
    key: 'DEPUTY_HEAD',
    title: 'Vice Principal / Dean',
    pack: 'INSTITUTION',
    rank: 2,
    kind: 'LINE',
    system: true,
    mayHoldReports: true,
    maxDelegableRank: 8,
    powerPresetId: 'preset-deputy-head',
    color: '#4472C4',
    icon: 'shield-alert',
    sortOrder: 2,
  },
  {
    key: 'REGISTRAR',
    title: 'Registrar / Academic Officer',
    pack: 'INSTITUTION',
    rank: 2,
    kind: 'STAFF',
    system: true,
    mayHoldReports: false,
    maxDelegableRank: 7,
    powerPresetId: 'preset-registrar',
    color: '#5B9BD5',
    icon: 'book-open',
    sortOrder: 3,
  },
  {
    key: 'EXAMINATION_OFFICER',
    title: 'Controller of Examinations',
    pack: 'INSTITUTION',
    rank: 2,
    kind: 'STAFF',
    system: true,
    mayHoldReports: false,
    maxDelegableRank: 7,
    powerPresetId: 'preset-examination-officer',
    color: '#70AD47',
    icon: 'clipboard-check',
    sortOrder: 4,
  },
  {
    key: 'ACCOUNTS_OFFICER',
    title: 'Accounts Officer / Bursar',
    pack: 'INSTITUTION',
    rank: 2,
    kind: 'STAFF',
    system: true,
    mayHoldReports: false,
    maxDelegableRank: 7,
    powerPresetId: 'preset-accounts-officer',
    color: '#FFC000',
    icon: 'credit-card',
    sortOrder: 5,
  },
  {
    key: 'DEPARTMENT_HEAD',
    title: 'Head of Department (HOD)',
    pack: 'INSTITUTION',
    rank: 3,
    kind: 'LINE',
    system: true,
    mayHoldReports: true,
    maxDelegableRank: 7,
    powerPresetId: 'preset-department-head',
    color: '#ED7D31',
    icon: 'briefcase',
    sortOrder: 6,
  },
  {
    key: 'PROGRAMME_COORDINATOR',
    title: 'Programme / Year Coordinator',
    pack: 'INSTITUTION',
    rank: 4,
    kind: 'LINE',
    system: true,
    mayHoldReports: false,
    maxDelegableRank: 6,
    powerPresetId: 'preset-programme-coordinator',
    color: '#C55A11',
    icon: 'list-checks',
    sortOrder: 7,
  },
  {
    key: 'CLASS_COORDINATOR',
    title: 'Class Teacher / Class Coordinator',
    pack: 'INSTITUTION',
    rank: 4,
    kind: 'LINE',
    system: true,
    mayHoldReports: false,
    maxDelegableRank: 5,
    powerPresetId: 'preset-class-coordinator',
    color: '#C55A11',
    icon: 'users',
    sortOrder: 8,
  },
  {
    key: 'FACULTY',
    title: 'Faculty / Subject Teacher',
    pack: 'INSTITUTION',
    rank: 4,
    kind: 'LINE',
    system: true,
    mayHoldReports: false,
    maxDelegableRank: 5,
    powerPresetId: 'preset-faculty',
    color: '#A64D79',
    icon: 'graduation-cap',
    sortOrder: 9,
  },
  {
    key: 'STUDENT_MENTOR',
    title: 'Student Mentor / Prefect',
    pack: 'INSTITUTION',
    rank: 5,
    kind: 'LINE',
    system: true,
    mayHoldReports: true,
    maxDelegableRank: 6,
    powerPresetId: 'preset-student-mentor',
    color: '#8E7CC3',
    icon: 'user-check',
    sortOrder: 10,
  },
  {
    key: 'STUDENT',
    title: 'Student',
    pack: 'INSTITUTION',
    rank: 6,
    kind: 'LINE',
    system: true,
    mayHoldReports: false,
    maxDelegableRank: 5,
    powerPresetId: 'preset-student',
    color: '#97B8F0',
    icon: 'user',
    sortOrder: 11,
  },
  {
    key: 'GUARDIAN',
    title: 'Parent / Guardian',
    pack: 'INSTITUTION',
    rank: 7,
    kind: 'EXTERNAL',
    system: true,
    mayHoldReports: false,
    maxDelegableRank: 0,
    powerPresetId: 'preset-guardian',
    color: '#BFBFBF',
    icon: 'home',
    sortOrder: 20,
  },
  {
    key: 'LIBRARIAN',
    title: 'Librarian',
    pack: 'INSTITUTION',
    rank: 7,
    kind: 'STAFF',
    system: true,
    mayHoldReports: false,
    maxDelegableRank: 0,
    powerPresetId: 'preset-librarian',
    color: '#595959',
    icon: 'book',
    sortOrder: 21,
  },
];

// Organisation Pack Roles (from §3.3)
export const ORGANISATION_ROLES: Omit<Role, 'id' | 'tenantId'>[] = [
  {
    key: 'PLATFORM_OPERATOR',
    title: 'Platform Operator',
    pack: 'ORGANISATION',
    rank: 0,
    kind: 'LINE',
    system: true,
    mayHoldReports: false,
    maxDelegableRank: 9,
    powerPresetId: 'preset-platform-operator',
    color: '#000000',
    icon: 'shield',
    sortOrder: 0,
  },
  {
    key: 'MANAGING_DIRECTOR',
    title: 'Owner / Managing Director',
    pack: 'ORGANISATION',
    rank: 1,
    kind: 'LINE',
    system: true,
    mayHoldReports: true,
    maxDelegableRank: 9,
    powerPresetId: 'preset-managing-director',
    color: '#366092',
    icon: 'crown',
    sortOrder: 1,
  },
  {
    key: 'OPERATIONS_DIRECTOR',
    title: 'COO / Operations Director',
    pack: 'ORGANISATION',
    rank: 2,
    kind: 'LINE',
    system: true,
    mayHoldReports: true,
    maxDelegableRank: 8,
    powerPresetId: 'preset-operations-director',
    color: '#4472C4',
    icon: 'trending-up',
    sortOrder: 2,
  },
  {
    key: 'HEAD_OF_PEOPLE',
    title: 'Head of People / HR Head',
    pack: 'ORGANISATION',
    rank: 2,
    kind: 'STAFF',
    system: true,
    mayHoldReports: false,
    maxDelegableRank: 7,
    powerPresetId: 'preset-head-of-people',
    color: '#5B9BD5',
    icon: 'users',
    sortOrder: 3,
  },
  {
    key: 'FINANCE_CONTROLLER',
    title: 'Finance Controller',
    pack: 'ORGANISATION',
    rank: 2,
    kind: 'STAFF',
    system: true,
    mayHoldReports: false,
    maxDelegableRank: 7,
    powerPresetId: 'preset-finance-controller',
    color: '#70AD47',
    icon: 'credit-card',
    sortOrder: 4,
  },
  {
    key: 'IT_ADMINISTRATOR',
    title: 'IT Administrator',
    pack: 'ORGANISATION',
    rank: 2,
    kind: 'STAFF',
    system: true,
    mayHoldReports: false,
    maxDelegableRank: 7,
    powerPresetId: 'preset-it-administrator',
    color: '#C55A11',
    icon: 'settings',
    sortOrder: 5,
  },
  {
    key: 'DEPARTMENT_MANAGER',
    title: 'Manager / Department Manager',
    pack: 'ORGANISATION',
    rank: 3,
    kind: 'LINE',
    system: true,
    mayHoldReports: true,
    maxDelegableRank: 7,
    powerPresetId: 'preset-department-manager',
    color: '#ED7D31',
    icon: 'briefcase',
    sortOrder: 6,
  },
  {
    key: 'TEAM_LEAD',
    title: 'Team Lead / Tech Lead',
    pack: 'ORGANISATION',
    rank: 4,
    kind: 'LINE',
    system: true,
    mayHoldReports: true,
    maxDelegableRank: 6,
    powerPresetId: 'preset-team-lead',
    color: '#C55A11',
    icon: 'badge',
    sortOrder: 7,
  },
  {
    key: 'SENIOR_MEMBER',
    title: 'Senior Engineer / Senior Associate',
    pack: 'ORGANISATION',
    rank: 5,
    kind: 'LINE',
    system: true,
    mayHoldReports: true,
    maxDelegableRank: 6,
    powerPresetId: 'preset-senior-member',
    color: '#A64D79',
    icon: 'star',
    sortOrder: 8,
  },
  {
    key: 'MEMBER',
    title: 'Employee / Associate',
    pack: 'ORGANISATION',
    rank: 6,
    kind: 'LINE',
    system: true,
    mayHoldReports: false,
    maxDelegableRank: 5,
    powerPresetId: 'preset-member',
    color: '#97B8F0',
    icon: 'user',
    sortOrder: 9,
  },
  {
    key: 'RECRUITER',
    title: 'Recruiter',
    pack: 'ORGANISATION',
    rank: 7,
    kind: 'STAFF',
    system: true,
    mayHoldReports: false,
    maxDelegableRank: 0,
    powerPresetId: 'preset-recruiter',
    color: '#8E7CC3',
    icon: 'briefcase',
    sortOrder: 20,
  },
  {
    key: 'PAYROLL_OFFICER',
    title: 'Payroll Officer',
    pack: 'ORGANISATION',
    rank: 7,
    kind: 'STAFF',
    system: true,
    mayHoldReports: false,
    maxDelegableRank: 0,
    powerPresetId: 'preset-payroll-officer',
    color: '#BFBFBF',
    icon: 'credit-card',
    sortOrder: 21,
  },
];

export const getAllRoles = (pack: 'INSTITUTION' | 'ORGANISATION'): Omit<Role, 'id' | 'tenantId'>[] => {
  return pack === 'INSTITUTION' ? INSTITUTION_ROLES : ORGANISATION_ROLES;
};
